In [1]:
import torch
from torch import Tensor
from torch.nn import Sequential, Linear, ReLU
from scipy.sparse import random
from scipy import stats
from numpy.random import default_rng
# circuit-sim
# import subcircuit as sc
# import PySpice.Logging.Logging as Logging
# logger = Logging.setup_logging()
# from PySpice.Spice.Netlist import Circuit, SubCircuit, SubCircuitFactory
# from PySpice.Unit import *
# from PySpice.Spice.NgSpice.Shared import NgSpiceShared


In [ ]:
class GNNModule(torch.nn.Module):
    def __init__(self, ...):
        super().__init__()

        self.conv = MyConv(...)
        # Use a global sort aggregation:
        self.global_pool = aggr.SortAggregation(k=4)
        self.classifier = torch.nn.Linear(...)

     def foward(self, x, edge_index, batch):
         pass

| Type | Value                          | Type | Value                              |
|------|--------------------------------|------|------------------------------------|
| Node | capacitance value              | Path | input transition time              |
|      | num of input nodes             |      | drive strength of drive cell       |
|      | total input cap                |      | functionality  of drive cell       |
|      | total output cap               |      | drive strength of load cell        |
|      | number of connected resistance |      | functionality of load cell         |
|      | total input resistance         |      | effective capacitance of load cell |
|      | total output resistance        |      | wire path Elmore delay             |
|      | Elmore downstream capacitance  |      | wire path D2M delay                |
|      | Elmore stage delay             |      |                                    |

In [13]:
# Random Number Generator
rng = default_rng(seed=42)
rvs = stats.poisson(2, loc=1).rvs

# Network Parameters
num_nodes = 4
num_node_features = 9
num_paths = 2
num_path_features = 8


# Node Feature Matrix X for each capacitanc : d_x x V
M_node = random(num_node_features, num_nodes, density=0.25, random_state=rng, data_rvs=rvs)
print(M_node.A)

# Path Feature Matrix H for each path : d_h x P
M_path = random(num_path_features, num_paths, density=0.25, random_state=rng, data_rvs=rvs)
print(M_path.A)

# Weighted Adjacency Matrix A (reistance between vIi and v_j) : V x V
M_adj = random(num_nodes, num_nodes, density=0.25, random_state=rng, data_rvs=rvs)
print(M_adj.A)


[[0. 0. 0. 0.]
 [0. 0. 4. 3.]
 [2. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 2. 3. 1.]
 [0. 0. 0. 0.]
 [0. 0. 2. 3.]
 [2. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 3.]
 [1. 0.]
 [0. 0.]
 [0. 5.]
 [0. 0.]
 [0. 0.]
 [2. 0.]
 [0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 4. 3.]
 [0. 4. 5. 0.]
 [0. 0. 0. 0.]]


In [14]:
from torch_geometric.datasets import Planetoid

dataset = Planetoid(root='.', name="Pubmed")
data = dataset[0]

Processing...
Done!


In [17]:
# Print information about the dataset
print(f'Dataset: {dataset}')
print('-------------------')
print(f'Number of graphs: {len(dataset)}')
print(f'Number of nodes: {data.x.shape[0]}')
print(f'Number of features: {dataset.num_features}')
print(f'Number of classes: {dataset.num_classes}')



Dataset: Pubmed()
-------------------
Number of graphs: 1
Number of nodes: 19717
Number of features: 500
Number of classes: 3
Pubmed()
